name: Build & Deploy to Release

on:
  push:
    branches:
      - main  # Runs only when main branch is updated

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Push only necessary files to release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan release
          git reset --hard
          
          # Move built files & package.json
          mv dist/* .  
          cp package.json .  # Copy package.json to release branch

          # Remove unnecessary files
          rm -rf dist/ .github/ node_modules/ src/

          git add .
          git commit -m "Auto-build dist for release"
          git push --force "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" release
